spring:
  application:
    name: DashDocsetApp

dash-docset:
  web-jar-temp-store-path: /app/temp
  docset-store-path: /app/docset
  javadocset-tool: /app/bin/javadocset
  zsh-working-dir: /app/temp
  enable-publish-web-jar-download-success-event: on

server:
  port: 8090

springdoc:
  api-docs:
    enabled: on
    version: openapi_3_1
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    supported-submit-methods: get, post
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: org.metanoia.dashdocsetapp